// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjL74WVUiRpUUTixCos50T7nxx0Iq6MmE',
    appId: '1:992100266525:android:9b138eec1718dd25eb0cf4',
    messagingSenderId: '992100266525',
    projectId: 'e-commerce-bfa1b',
    databaseURL: 'https://e-commerce-bfa1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-bfa1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQKdORDXHdyFe6y4yPyFcj4Mpnbj8X-o',
    appId: '1:992100266525:ios:7145ce5220911045eb0cf4',
    messagingSenderId: '992100266525',
    projectId: 'e-commerce-bfa1b',
    databaseURL: 'https://e-commerce-bfa1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-bfa1b.firebasestorage.app',
    androidClientId: '992100266525-q8sl9ld7hloeaghgf3ehgaps3mfof626.apps.googleusercontent.com',
    iosClientId: '992100266525-vvc4k288q7jnb526hlgiifdfip3u9pk1.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.todoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhglSXZRuAjfkRZWdbzPHCXySVXZkjtng',
    appId: '1:992100266525:web:4df664f98407e140eb0cf4',
    messagingSenderId: '992100266525',
    projectId: 'e-commerce-bfa1b',
    authDomain: 'e-commerce-bfa1b.firebaseapp.com',
    databaseURL: 'https://e-commerce-bfa1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-bfa1b.firebasestorage.app',
    measurementId: 'G-LWHJGBX3EX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQKdORDXHdyFe6y4yPyFcj4Mpnbj8X-o',
    appId: '1:992100266525:ios:7145ce5220911045eb0cf4',
    messagingSenderId: '992100266525',
    projectId: 'e-commerce-bfa1b',
    databaseURL: 'https://e-commerce-bfa1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-bfa1b.firebasestorage.app',
    androidClientId: '992100266525-q8sl9ld7hloeaghgf3ehgaps3mfof626.apps.googleusercontent.com',
    iosClientId: '992100266525-vvc4k288q7jnb526hlgiifdfip3u9pk1.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.todoApp',
  );

}